### PR TITLE
feat: update brand guidelines to reflect rebranding

### PR DESCRIPTION
**Pull request by Charlotteis**
Bringing uStyle in line with out new branding!

1. Updates the logo blue to our new blue colour
2. Updates the logo guidelines to include new logos + newly worded usage guidelines
3. Updates us-icon to be 5 colours of our shiny new logo

🌞

### CODE REVIEW

**Comment by greenie** [comment]
gonna review dis

**Comment by annez** [comment]
@greenie hold off, I'm making changes to it

**Comment by annez** [comment]
@greenie good to review

**Comment by greenie** [comment]
LGTM 🚢

**Pull request merged**
